# Generated by Django 5.0.4 on 2024-06-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='holidays',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
