# Generated by Django 5.0.4 on 2024-06-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0011_batches_business_profile'),
        ('user_profile', '0030_remove_customer_is_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInventoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_link_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.businessprofile')),
                ('products', models.ManyToManyField(to='inventory.product')),
            ],
            options={
                'indexes': [models.Index(fields=['unique_link_code'], name='online_stor_unique__002f7a_idx'), models.Index(fields=['business_profile'], name='online_stor_busines_c9d7a3_idx')],
            },
        ),
    ]
