# Generated by Django 4.2.7 on 2023-11-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_userprofile_password_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
