# Generated by Django 4.2.7 on 2023-12-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_customer_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
