# Generated by Django 4.2.8 on 2024-02-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_menu', '0002_brand_producttype_size'),
        ('user_profile', '0013_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_menu.businesstype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='industry_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
