# Generated by Django 4.2.8 on 2024-02-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_menu', '0003_businesstype_type_industry_type'),
        ('user_profile', '0014_businessprofile_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='industry_type',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_menu.businesstype'),
        ),
    ]
