# Generated by Django 4.2.8 on 2024-02-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_menu', '0003_businesstype_type_industry_type'),
        ('user_profile', '0016_businessprofile_other_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='other_business_type',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='other_industry_type',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_menu.businesstype'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_menu.industry'),
        ),
    ]
