# Generated by Django 4.2.8 on 2024-02-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_menu', '0003_businesstype_type_industry_type'),
        ('user_profile', '0020_businessprofile_other_industry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='other_business_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other_business_profiles', to='master_menu.businesstype'),
            preserve_default=False,
        ),
    ]
