# Generated by Django 4.2.8 on 2024-02-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_businessprofile_other_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='other_business_type',
        ),
    ]
