# Generated by Django 4.2.8 on 2024-02-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0024_alter_businessprofile_other_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='other_business_type',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='other_industry_type',
        ),
    ]
