# Generated by Django 4.2.8 on 2024-02-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_menu', '0003_businesstype_type_industry_type'),
        ('user_profile', '0025_remove_businessprofile_other_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='other_business_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_business_profiles', to='master_menu.businesstype'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='other_industry_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_industry_profiles', to='master_menu.industry'),
        ),
    ]