# Generated by Django 5.0.4 on 2024-04-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_businessprofile_other_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
