# Generated by Django 5.0.4 on 2024-05-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_businessprofile_is_deleted_customer_is_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_purchase',
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=100)),
                ('zipcode', models.CharField(default=None, max_length=100)),
                ('phone_number', models.CharField(default=None, max_length=20)),
                ('gst_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('favourite', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.businessprofile')),
            ],
        ),
    ]
