# Generated by Django 5.0.4 on 2024-05-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_businessprofile_is_deleted_customer_is_purchase'),
        ('user_profile', '0027_customer_is_purchase'),
    ]

    operations = [
    ]
