# Generated by Django 5.0.4 on 2024-06-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0028_merge_20240521_1024'),
        ('user_profile', '0028_remove_customer_is_purchase_vendor'),
    ]

    operations = [
    ]
