# Generated by Django 5.0.4 on 2024-06-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0029_merge_20240603_1909'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='is_purchase',
        # ),
    ]
