# Generated by Django 4.2.7 on 2023-12-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
