# Generated by Django 4.2.7 on 2023-12-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remaining_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
