# Generated by Django 4.2.8 on 2024-01-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_remaining_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Invoice_pdf',
            field=models.FileField(default='demo.pdf', upload_to=''),
            preserve_default=False,
        ),
    ]
