# Generated by Django 4.2.8 on 2024-01-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_invoice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoice_pdf/'),
        ),
    ]
