# Generated by Django 4.2.8 on 2024-01-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
