# Generated by Django 4.2.8 on 2024-01-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_grand_total_invoice_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_option',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
