# Generated by Django 4.2.8 on 2024-01-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_payment_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='paid_amount',
        ),
    ]
