# Generated by Django 5.0.4 on 2024-05-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_rename_total_invoice_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
