# Generated by Django 5.0.4 on 2024-05-20 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_product_bar_code_number_and_more'),
        ('invoice', '0009_invoice_is_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.batches'),
        ),
    ]
