# Generated by Django 5.0.4 on 2024-07-18 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_menu', '0003_businesstype_type_industry_type'),
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=None, max_length=50)),
                ('brand', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.businessprofile')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_menu.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('total_quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('remaining_quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('sales_price', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('mrp_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('add_margin', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('status', models.IntegerField(blank=True, default=None, null=True)),
                ('bar_code_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('hsn_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('batch_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('package', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.businessprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
        ),
    ]
