# Generated by Django 4.2.7 on 2023-12-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_brand_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='remaining_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
