# Generated by Django 4.2.8 on 2024-01-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_quantity_product_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='BAR_code_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
