# Generated by Django 4.2.8 on 2024-02-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_bar_code_number_product_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
