# Generated by Django 4.2.8 on 2024-02-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_hsn_number_product_mrp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
