# Generated by Django 4.2.8 on 2024-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
