# Generated by Django 4.2.8 on 2024-03-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
