# Generated by Django 5.0.4 on 2024-05-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='BAR_code_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='add_margin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hsn_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mrp_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_quantity',
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('total_quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('remaining_quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('sales_price', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('mrp_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('add_margin', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('status', models.IntegerField(blank=True, default=None, null=True)),
                ('bar_code_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('hsn_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('batch_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('package', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
        ),
    ]
