# Generated by Django 5.0.4 on 2024-05-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_product_bar_code_number_and_more'),
        # ('user_profile', '0028_remove_customer_is_purchase_vendor'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='batches',
        #     name='business_profile',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.businessprofile'),
        # ),
    ]
